version: '3'

services:
  nestapp:
    container_name: nestapp

    image: nestapp:1.0.0

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./:/app
      - /app/node_modules
      - /app/dist

    environment:
      - NODE_ENV=development

    command: yarn listen  #yarn developper